### ISSUE TITLE
Opening in browser is broken from latest Ramda docs update

### ISSUE THREAD

**Issue by raine** [raine/alfred-ramda-workflow#1]
URL such as http://ramdajs.com/docs/#invoker no longer works, instead the version now needs to be included in the URL.

Unless the previous behavior resumes working, this workflow and also https://github.com/raine/ramda-json-docs needs to be updated to contain version number in each JSON.

**Comment by buzzdecafe** [comment]
fixed this in https://github.com/ramda/ramda.github.io/pull/3

please lmk if that works

**Comment by raine** [comment]
It's working. Thanks a lot!
